const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let controller=null, installed=new Set(), searchRows=[];
const state={messages:JSON.parse(localStorage.getItem('lai.messages')||'[]'),settings:JSON.parse(localStorage.getItem('lai.settings')||'{"system":"You are a helpful local AI assistant.","temperature":0.7}')};
async function j(url,opt){let r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.json()}
async function health(){let x=await j('/api/health');$('#dot').classList.toggle('ok',x.ollama);$('#statusText').textContent=x.ollama?'Ollama connected':'Ollama offline';return x.ollama}
async function loadModels(){let x=await j('/api/models'),s=$('#modelSelect');installed=new Set((x.models||[]).map(m=>m.name));let old=s.value;s.innerHTML='';if(!x.models.length){s.innerHTML='<option>No models installed</option>';$('#send').disabled=true;return}s.add(new Option('Select local model…',''));x.models.forEach(m=>s.add(new Option(`${m.name} (${formatBytes(m.size)})`,m.name)));if(installed.has(old))s.value=old;$('#send').disabled=false}
function formatBytes(n){if(!n)return '';let u=['B','KB','MB','GB','TB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return (n/1024**i).toFixed(i>2?1:0)+' '+u[i]}
function render(){let box=$('#messages');box.innerHTML=state.messages.length?'':'<div class="hero"><h1>Your local AI workbench</h1><p>Find a local model in Model Library, install it with Ollama, then start chatting.</p></div>';state.messages.forEach(m=>{let d=document.createElement('div');d.className='msg '+m.role;d.textContent=m.content;box.appendChild(d)});box.scrollTop=box.scrollHeight}
async function send(){let p=$('#prompt').value.trim(),model=$('#modelSelect').value;if(!p||!model||model==='No models installed')return;state.messages.push({role:'user',content:p});$('#prompt').value='';render();let a={role:'assistant',content:''};state.messages.push(a);render();controller=new AbortController();$('#stop').hidden=false;$('#send').hidden=true;try{let r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({model,messages:state.messages.slice(0,-1),system:state.settings.system,temperature:state.settings.temperature})});if(!r.ok)throw new Error(await r.text());let rd=r.body.getReader(),dec=new TextDecoder();while(true){let {value,done}=await rd.read();if(done)break;a.content+=dec.decode(value,{stream:true});render()}}catch(e){if(e.name!=='AbortError')a.content+='\n[Error: '+e.message+']'}finally{controller=null;$('#stop').hidden=true;$('#send').hidden=false;localStorage.setItem('lai.messages',JSON.stringify(state.messages));render()}}
async function searchCatalog(){let box=$('#catalog'),q=$('#modelQuery').value.trim();box.innerHTML='<div class="empty">Searching Ollama…</div>';try{let x=await j('/api/catalog/search?q='+encodeURIComponent(q));searchRows=x.models||[];renderFamilies()}catch(e){box.innerHTML='<div class="empty">Search failed: '+esc(e.message)+'</div>'}}
function renderFamilies(){let box=$('#catalog'),rows=[...searchRows];if($('#sortModels').value==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));else rows.sort((a,b)=>(b.downloads_value||0)-(a.downloads_value||0));if(!rows.length){box.innerHTML='<div class="empty">No matching Ollama models found. Try another model family name.</div>';return}box.innerHTML='';rows.forEach(m=>{let d=document.createElement('article');d.className='family';d.innerHTML=`<div class="family-summary"><div><h3>${esc(m.name)}</h3><div class="chips">${(m.capabilities||[]).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div><p>${esc(m.description||'Ollama model family')}</p><div class="meta">${m.downloads?'Downloads: '+esc(m.downloads):''}${m.updated?' · Updated '+esc(m.updated):''}</div></div><button class="details">Show variants</button></div><div class="variants" hidden></div>`;d.querySelector('.details').onclick=()=>toggleDetail(m,d);box.appendChild(d)})}
async function toggleDetail(m,card){let area=card.querySelector('.variants'),btn=card.querySelector('.details');if(!area.hidden){area.hidden=true;btn.textContent='Show variants';return}area.hidden=false;btn.textContent='Hide variants';if(area.dataset.loaded)return;area.innerHTML='<div class="meta" style="padding:14px 0">Loading published Ollama variants…</div>';try{let x=await j('/api/catalog/model/'+encodeURIComponent(m.name));let variants=$('#localOnly').checked?x.local_variants:x.variants;area.innerHTML='';if(!variants.length){area.innerHTML='<div class="meta" style="padding:14px 0">No locally downloadable variants with published size were found.</div>';return}variants.forEach(v=>area.appendChild(variantRow(v)));area.dataset.loaded='1'}catch(e){area.innerHTML='<div class="meta" style="padding:14px 0">Could not load variants: '+esc(e.message)+'</div>'}}
function variantRow(v){let row=document.createElement('div');row.className='variant';let isInstalled=installed.has(v.tag);row.innerHTML=`<div class="variant-name">${esc(v.tag)}</div><div>${esc(v.size)}</div><div>${esc(v.context)} context</div><div>${esc(v.input)}</div><div>${isInstalled?'<span class="installed">✓ Installed</span>':v.local?'<button class="pull">Download</button>':'<span class="meta">Cloud / unavailable locally</span>'}</div><div class="progress"><div class="bar"></div></div><div class="meta ptext">${esc(v.updated||'')}</div>`;let b=row.querySelector('.pull');if(b)b.onclick=()=>pull(v.tag,row);return row}
async function pull(name,row){let b=row.querySelector('.pull'),bar=row.querySelector('.bar'),txt=row.querySelector('.ptext');b.disabled=true;txt.textContent='Starting download…';try{let r=await fetch('/api/pull',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});if(!r.ok)throw new Error(await r.text());let rd=r.body.getReader(),dec=new TextDecoder(),buf='';while(true){let {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});let lines=buf.split('\n');buf=lines.pop();for(let line of lines){if(!line)continue;let x=JSON.parse(line);txt.textContent=x.status||'Downloading…';if(x.total&&x.completed)bar.style.width=Math.round(x.completed/x.total*100)+'%'}}txt.textContent='Installed successfully.';bar.style.width='100%';await loadModels();b.replaceWith(Object.assign(document.createElement('span'),{className:'installed',textContent:'✓ Installed'}))}catch(e){txt.textContent='Download failed: '+e.message;b.disabled=false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='models'&&!searchRows.length)searchCatalog()});$('#send').onclick=send;$('#stop').onclick=()=>controller?.abort();$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#newChat').onclick=()=>{state.messages=[];localStorage.removeItem('lai.messages');render()};$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('lai.dark',document.body.classList.contains('dark'))};$('#temp').oninput=e=>$('#tempVal').textContent=e.target.value;$('#saveSettings').onclick=()=>{state.settings={system:$('#system').value,temperature:+$('#temp').value};localStorage.setItem('lai.settings',JSON.stringify(state.settings))};$('#searchForm').onsubmit=e=>{e.preventDefault();searchCatalog()};$('#refreshCatalog').onclick=searchCatalog;$('#sortModels').onchange=renderFamilies;$('#localOnly').onchange=()=>{document.querySelectorAll('.variants').forEach(x=>{x.dataset.loaded='';x.hidden=true});document.querySelectorAll('.details').forEach(x=>x.textContent='Show variants')};
if(localStorage.getItem('lai.dark')==='true')document.body.classList.add('dark');$('#system').value=state.settings.system;$('#temp').value=state.settings.temperature;$('#tempVal').textContent=state.settings.temperature;render();health().then(loadModels).catch(()=>{$('#statusText').textContent='Backend/Ollama unavailable'});
